# Generated by Django 5.1.4 on 2025-01-10 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_alter_clientservice_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_usage', models.BigIntegerField(help_text='Download usage in bytes', verbose_name='download usage (bytes)')),
                ('upload_usage', models.BigIntegerField(help_text='Upload usage in bytes', verbose_name='upload usage (bytes)')),
                ('timestamp', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_usage', to='services.clientservice')),
            ],
            options={
                'verbose_name': 'bandwidth usage',
                'verbose_name_plural': 'bandwidth usage records',
                'db_table': 'bandwidth_usage',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service', 'timestamp'], name='bandwidth_u_service_7f8e72_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_download', models.BigIntegerField()),
                ('total_upload', models.BigIntegerField()),
                ('peak_download_speed', models.BigIntegerField()),
                ('peak_upload_speed', models.BigIntegerField()),
                ('average_download_speed', models.BigIntegerField()),
                ('average_upload_speed', models.BigIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='services.clientservice')),
            ],
            options={
                'verbose_name': 'daily usage summary',
                'verbose_name_plural': 'daily usage summaries',
                'db_table': 'daily_usage_summary',
                'ordering': ['-date'],
                'unique_together': {('service', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_download', models.BigIntegerField()),
                ('total_upload', models.BigIntegerField()),
                ('peak_day', models.DateField()),
                ('peak_download', models.BigIntegerField()),
                ('peak_upload', models.BigIntegerField()),
                ('average_daily_download', models.BigIntegerField()),
                ('average_daily_upload', models.BigIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage', to='services.clientservice')),
            ],
            options={
                'db_table': 'monthly_usage_summary',
                'ordering': ['-year', '-month'],
                'unique_together': {('service', 'year', 'month')},
            },
        ),
    ]
